#!/bin/sh
set -e

# Option -r removes autogenerated files.
if test x"$1" = x-r; then
  rm -Rf lib m4 build-aux autom4te.cache
  rm -f configure aclocal.m4 INSTALL
  for dir in . src yambi; do rm -f $dir/Makefile.in; done
  exit
fi

set -x
gnulib-tool --add-import pthread utimens warnings timespec-add timespec-sub \
    dtotimespec stat-time lstat malloc-gnu fprintf-posix inttypes

aclocal -Im4
autoconf
autoheader
automake --add-missing --copy
